In [90]:
import pandas as pd
import numpy as np

In [91]:
konsi_sc = pd.read_csv('exports/beli_konsi_sc.csv')
konsi_sap = pd.read_csv('exports/beli_konsi_sap.csv')
reg_sc = pd.read_csv('exports/beli_reg_sc.csv')
reg_sap = pd.read_csv('exports/beli_reg_sap.csv')
retur_sc = pd.read_csv('exports/beli_retur_sc.csv')
retur_sap = pd.read_csv('exports/beli_retur_sap.csv')
kreditur = pd.read_csv('exports/dim_kreditur.csv')
outlet = pd.read_csv('exports/dim_outlet.csv')

In [92]:
konsi_sc

,kode_outlet,no_transaksi,kode_obat,liph_date,segmen,hna,qty_jual,disc_margin,disc_principal,disc_principal_val,total_bayar,harga_jual,harga_srp,kode_supplier
0,BX01,T1112NJ0342235671E,13077027,4/20/2025,HV,180000,1,28.2,12.5,0.0,106740,144000,180000,1000003862
1,BX01,T1112NJ03422384578,13081421,4/20/2025,HV,42735,1,28.0,0.0,0.0,30769,42735,42735,1000002568
2,BX01,T1112NJ03422384578,13084535,4/20/2025,HV,140000,1,28.2,12.5,0.0,83020,112000,140000,1000003862
3,BX01,T1112NJ03422411423,13077027,4/20/2025,HV,180000,1,28.2,12.5,0.0,106740,144000,180000,1000003862
4,BX01,T1112NJ0342242280M,13084223,4/20/2025,HV,50000,1,20.0,0.0,0.0,40000,50000,50000,1000003862
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43343,BX52,T1114YY0345585764D,13077027,5/19/2025,RESEP TUNAI,180000,1,28.2,12.5,0.0,106740,144000,180000,1000003862
43344,BX52,T1114YY0345594954E,13073543,5/19/2025,UPDS,10900,1,42.2,0.0,0.0,6300,10900,10900,1000005987
43345,BX52,T1114YY0345600287R,13095063,5/19/2025,HV,25500,1,28.5,10.0,0.0,15682,22950,25500,1000009726
43346,BX52,T1114YY0345650212D,13087043,5/20/2025,UPDS,359640,1,29.0,0.0,0.0,255344,359640,359640,1000002392
43347,BX52,T1114YY0345704647L,13022015,5/20/2025,UPDS,76035,1,29.0,0.0,0.0,53985,76035,76035,1000002392

In [93]:
konsi_sap

,profit_center,document_date,posting_date,assignment,gl_account,text,doc_number,doc_type,posting_key,amount
0,3150,1/31/2025,1/31/2025,22,5101020102,BHARADAH SAKTI PT KONSINYASI,100016689,SA,50,-467549
1,3150,1/31/2025,1/31/2025,40,5101020102,"ABAD DUA SATU MAKMUR, CV KONSINYASI",100016707,SA,50,-224922
2,3150,1/31/2025,1/31/2025,105,5101020102,BHARADAH SAKTI PT KONSINYASI,100016772,SA,50,-43806
3,3150,1/31/2025,1/31/2025,173,5101020102,"INTI CITRA AGUNG, PT KONSINYASI",100016840,SA,40,13201
4,3150,1/31/2025,1/31/2025,213,5101020102,"MARKETING BERKAT INDONESIA, PT KONSINYASI",100016880,SA,40,290400
...,...,...,...,...,...,...,...,...,...,...
5685,BX50,5/31/2025,5/31/2025,20250531,5101020102,NaN,601151742,QA,40,831064
5686,BX51,5/31/2025,5/31/2025,20250531,5101020102,NaN,601151743,QA,40,652652
5687,BX52,5/31/2025,5/31/2025,20250531,5101020102,NaN,601151744,QA,40,1010093
5688,BX35,5/31/2025,5/31/2025,20250531,5101020102,NaN,3800016251,Z8,40,146914
5689,BX03,5/31/2025,5/31/2025,20250531,5101020102,NaN,3800016252,Z8,40,207737

## Dataset Note:
--- 
### Konsi
Grouping antara Outlet dan Tanggal, Validasi \
SAP: Amount  ==  SC: Total Bayar\
Dalam Konsi SAP itu ada yang input manual, olah layaknya 

### Reg
Grouping antara Outlet dan Tanggal, Validasi \
SAP = Debit \
SC = jml_neto \
Untuk Missing Data, jangan dihapus, tapi dipindahkan agar dapat mencatat insight dari data tersebut

### Retur
Grouping antara Outlet dan Tanggal, Validasi\
SAP = Kredit \
SC = Jumlah Retur

In [82]:
kolom_tanggal_konsi_a = 'liph_date'
kolom_tanggal_konsi_b = 'posting_date'


konsi_b[kolom_tanggal_konsi_b] = pd.to_datetime(konsi_b[kolom_tanggal_konsi_b], errors='coerce')
konsi_a[kolom_tanggal_konsi_a] = pd.to_datetime(konsi_a[kolom_tanggal_konsi_a], errors='coerce')

In [83]:
konsi_a.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43348 entries, 0 to 43347
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   kode_outlet         43348 non-null  object
 1   no_transaksi        43348 non-null  object
 2   kode_obat           43348 non-null  int64
 3   liph_date           43348 non-null  datetime64[ns]
 4   segmen              43348 non-null  object
 5   hna                 43348 non-null  int64
 6   qty_jual            43348 non-null  int64
 7   disc_margin         43348 non-null  float64
 8   disc_principal      43348 non-null  float64
 9   disc_principal_val  43348 non-null  float64
 10  total_bayar         43348 non-null  int64
 11  harga_jual          43348 non-null  int64
 12  harga_srp           43348 non-null  int64
 13  kode_supplier       43348 non-null  int64
dtypes: datetime64[ns](1), float64(3), int64(7), object(3)
memory usage: 4.6+ MB

In [89]:
konsi_b.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5690 entries, 0 to 5689
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   kode_outlet    5690 non-null   object
 1   document_date  5690 non-null   object
 2   posting_date   5690 non-null   datetime64[ns]
 3   assignment     5690 non-null   int64
 4   gl_account     5690 non-null   int64
 5   text           46 non-null     object
 6   doc_number     5690 non-null   int64
 7   doc_type       5690 non-null   object
 8   posting_key    5690 non-null   int64
 9   amount         5690 non-null   int64
dtypes: datetime64[ns](1), int64(5), object(4)
memory usage: 444.7+ KB

In [84]:
konsi_b = konsi_b.rename(columns={
    'profit_center': 'kode_outlet'})

In [85]:
kolom_kunci = 'kode_outlet'

df_gabungan = pd.merge(
    konsi_b,
    konsi_a,
    on=kolom_kunci,
    how='outer',
    suffixes=('_sap', '_sc')
)

print("\nContoh data setelah digabungkan:")
print(df_gabungan.head())

Contoh data setelah digabungkan:
  kode_outlet document_date posting_date  assignment  gl_account  \
0        3150     1/31/2025   2025-01-31          22  5101020102
1        3150     1/31/2025   2025-01-31          40  5101020102
2        3150     1/31/2025   2025-01-31         105  5101020102
3        3150     1/31/2025   2025-01-31         173  5101020102
4        3150     1/31/2025   2025-01-31         213  5101020102

                                         text  doc_number doc_type  \
0                BHARADAH SAKTI PT KONSINYASI   100016689       SA
1         ABAD DUA SATU MAKMUR, CV KONSINYASI   100016707       SA
2                BHARADAH SAKTI PT KONSINYASI   100016772       SA
3             INTI CITRA AGUNG, PT KONSINYASI   100016840       SA
4  MARKETING BERKAT INDONESIA, PT  KONSINYASI   100016880       SA

   posting_key  amount  ... segmen  hna qty_jual disc_margin  disc_principal  \
0           50 -467549  ...    NaN  NaN      NaN         NaN             NaN
1           50 -224922  ...    NaN  NaN      NaN         NaN             NaN
2           50  -43806  ...    NaN  NaN      NaN         NaN             NaN
3           40   13201  ...    NaN  NaN      NaN         NaN             NaN
4           40  290400  ...    NaN  NaN      NaN         NaN             NaN

   disc_principal_val  total_bayar  harga_jual  harga_srp  kode_supplier
0                 NaN          NaN         NaN        NaN            NaN
1                 NaN          NaN         NaN        NaN            NaN
2                 NaN          NaN         NaN        NaN            NaN
3                 NaN          NaN         NaN        NaN            NaN
4                 NaN          NaN         NaN        NaN            NaN

[5 rows x 23 columns]

In [86]:
conditions = [
    (df_gabungan[kolom_tanggal_konsi_a] == df_gabungan[kolom_tanggal_konsi_b]), # Kondisi 1: Tanggal sama
    (df_gabungan[kolom_tanggal_konsi_a].isnull()) | (df_gabungan[kolom_tanggal_konsi_b].isnull()), # Kondisi 2: Salah satu data tidak ada
]
choices = [
    'Sesuai',           # Hasil jika Kondisi 1 benar
    'Data Tidak Lengkap' # Hasil jika Kondisi 2 benar
]

df_gabungan['Status_Validasi'] = np.select(conditions, choices, default='Tidak Sesuai')

print("\nData dengan Status Validasi:")
print(df_gabungan.head())

Data dengan Status Validasi:
  kode_outlet document_date posting_date  assignment  gl_account  \
0        3150     1/31/2025   2025-01-31          22  5101020102
1        3150     1/31/2025   2025-01-31          40  5101020102
2        3150     1/31/2025   2025-01-31         105  5101020102
3        3150     1/31/2025   2025-01-31         173  5101020102
4        3150     1/31/2025   2025-01-31         213  5101020102

                                         text  doc_number doc_type  \
0                BHARADAH SAKTI PT KONSINYASI   100016689       SA
1         ABAD DUA SATU MAKMUR, CV KONSINYASI   100016707       SA
2                BHARADAH SAKTI PT KONSINYASI   100016772       SA
3             INTI CITRA AGUNG, PT KONSINYASI   100016840       SA
4  MARKETING BERKAT INDONESIA, PT  KONSINYASI   100016880       SA

   posting_key  amount  ... hna  qty_jual disc_margin disc_principal  \
0           50 -467549  ... NaN       NaN         NaN            NaN
1           50 -224922  ... NaN       NaN         NaN            NaN
2           50  -43806  ... NaN       NaN         NaN            NaN
3           40   13201  ... NaN       NaN         NaN            NaN
4           40  290400  ... NaN       NaN         NaN            NaN

   disc_principal_val  total_bayar  harga_jual  harga_srp  kode_supplier  \
0                 NaN          NaN         NaN        NaN            NaN
1                 NaN          NaN         NaN        NaN            NaN
2                 NaN          NaN         NaN        NaN            NaN
3                 NaN          NaN         NaN        NaN            NaN
4                 NaN          NaN         NaN        NaN            NaN

      Status_Validasi
0  Data Tidak Lengkap
1  Data Tidak Lengkap
2  Data Tidak Lengkap
3  Data Tidak Lengkap
4  Data Tidak Lengkap

[5 rows x 24 columns]

In [87]:
df_gabungan

,kode_outlet,document_date,posting_date,assignment,gl_account,text,doc_number,doc_type,posting_key,amount,...,hna,qty_jual,disc_margin,disc_principal,disc_principal_val,total_bayar,harga_jual,harga_srp,kode_supplier,Status_Validasi
0,3150,1/31/2025,2025-01-31,22,5101020102,BHARADAH SAKTI PT KONSINYASI,100016689,SA,50,-467549,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Data Tidak Lengkap
1,3150,1/31/2025,2025-01-31,40,5101020102,"ABAD DUA SATU MAKMUR, CV KONSINYASI",100016707,SA,50,-224922,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Data Tidak Lengkap
2,3150,1/31/2025,2025-01-31,105,5101020102,BHARADAH SAKTI PT KONSINYASI,100016772,SA,50,-43806,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Data Tidak Lengkap
3,3150,1/31/2025,2025-01-31,173,5101020102,"INTI CITRA AGUNG, PT KONSINYASI",100016840,SA,40,13201,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Data Tidak Lengkap
4,3150,1/31/2025,2025-01-31,213,5101020102,"MARKETING BERKAT INDONESIA, PT KONSINYASI",100016880,SA,40,290400,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Data Tidak Lengkap
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7295286,BX52,5/31/2025,2025-05-31,20250531,5101020102,NaN,601151744,QA,40,1010093,...,180000.0,1.0,28.2,12.5,0.0,106740.0,144000.0,180000.0,1.000004e+09,Tidak Sesuai
7295287,BX52,5/31/2025,2025-05-31,20250531,5101020102,NaN,601151744,QA,40,1010093,...,10900.0,1.0,42.2,0.0,0.0,6300.0,10900.0,10900.0,1.000006e+09,Tidak Sesuai
7295288,BX52,5/31/2025,2025-05-31,20250531,5101020102,NaN,601151744,QA,40,1010093,...,25500.0,1.0,28.5,10.0,0.0,15682.0,22950.0,25500.0,1.000010e+09,Tidak Sesuai
7295289,BX52,5/31/2025,2025-05-31,20250531,5101020102,NaN,601151744,QA,40,1010093,...,359640.0,1.0,29.0,0.0,0.0,255344.0,359640.0,359640.0,1.000002e+09,Tidak Sesuai
7295290,BX52,5/31/2025,2025-05-31,20250531,5101020102,NaN,601151744,QA,40,1010093,...,76035.0,1.0,29.0,0.0,0.0,53985.0,76035.0,76035.0,1.000002e+09,Tidak Sesuai